"""true_msisdn field for soaplogs

Revision ID: 0688943ace65
Revises: 55c2de672362
Create Date: 2025-07-31 17:04:33.399355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0688943ace65'
down_revision: Union[str, Sequence[str], None] = '55c2de672362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soaplogs', sa.Column('true_msisdn', sa.BigInteger(), nullable=True))
    op.create_index('soap_msisdn_index', 'soaplogs', ['true_msisdn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('soap_msisdn_index', table_name='soaplogs')
    op.drop_column('soaplogs', 'true_msisdn')
    # ### end Alembic commands ###
