"""true_imsi, true_msisdn fields and indexes

Revision ID: 0be93f57379e
Revises: be34808785da
Create Date: 2025-07-15 14:49:02.158535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be93f57379e'
down_revision: Union[str, Sequence[str], None] = 'be34808785da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentlogs', sa.Column('true_imsi', sa.Integer(), nullable=True))
    op.add_column('agentlogs', sa.Column('true_msisdn', sa.Integer(), nullable=True))
    op.create_index('imsi_index', 'agentlogs', ['true_imsi'], unique=False)
    op.create_index('msisdn_index', 'agentlogs', ['true_msisdn'], unique=False)
    op.create_index('time_index', 'agentlogs', ['log_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('time_index', table_name='agentlogs')
    op.drop_index('msisdn_index', table_name='agentlogs')
    op.drop_index('imsi_index', table_name='agentlogs')
    op.drop_column('agentlogs', 'true_msisdn')
    op.drop_column('agentlogs', 'true_imsi')
    # ### end Alembic commands ###
