"""node_name field in log tables

Revision ID: 4037a8381ee9
Revises: 98e22eb1f76a
Create Date: 2025-07-30 14:44:33.766471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4037a8381ee9'
down_revision: Union[str, Sequence[str], None] = '98e22eb1f76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentlogs', sa.Column('node_name', sa.String(), nullable=False))
    op.add_column('commandlogs', sa.Column('node_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commandlogs', 'node_name')
    op.drop_column('agentlogs', 'node_name')
    # ### end Alembic commands ###
