"""new model for soaplogs

Revision ID: 55c2de672362
Revises: 4037a8381ee9
Create Date: 2025-07-31 16:35:26.598031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c2de672362'
down_revision: Union[str, Sequence[str], None] = '4037a8381ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soaplogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_time', sa.DateTime(), nullable=False),
    sa.Column('cmd_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('if_error', sa.Boolean(), nullable=False),
    sa.Column('error_description', sa.String(), nullable=True),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('soaplog_time_index', 'soaplogs', ['log_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('soaplog_time_index', table_name='soaplogs')
    op.drop_table('soaplogs')
    # ### end Alembic commands ###
