"""CommandLogModel

Revision ID: 98e22eb1f76a
Revises: a10efb665080
Create Date: 2025-07-21 15:50:52.137685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e22eb1f76a'
down_revision: Union[str, Sequence[str], None] = 'a10efb665080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commandlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('function', sa.String(), nullable=False),
    sa.Column('user_ip', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('log_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('commandlog_time_index', 'commandlogs', ['log_time'], unique=False)
    op.create_index('username_index', 'commandlogs', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username_index', table_name='commandlogs')
    op.drop_index('commandlog_time_index', table_name='commandlogs')
    op.drop_table('commandlogs')
    # ### end Alembic commands ###
