"""adding agentlog table

Revision ID: be34808785da
Revises: 
Create Date: 2025-07-11 13:36:31.217735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be34808785da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmd_code', sa.String(), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.Column('imsi', sa.String(), nullable=True),
    sa.Column('msisdn', sa.String(), nullable=True),
    sa.Column('log_time', sa.DateTime(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('agent_type', sa.Integer(), nullable=False),
    sa.Column('node_ip', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('if_error', sa.Boolean(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agentlogs')
    # ### end Alembic commands ###
